# Generated by Django 2.1.7 on 2020-06-13 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conjunto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificação', models.CharField(max_length=200)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('obs', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Equipamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_de_serie', models.CharField(blank=True, max_length=100)),
                ('patrimonio', models.CharField(blank=True, max_length=100, null=True)),
                ('departamento', models.CharField(blank=True, max_length=100, null=True)),
                ('mesa', models.CharField(blank=True, max_length=50, null=True)),
                ('ramal_proximo', models.CharField(blank=True, max_length=50, null=True)),
                ('usuario', models.CharField(blank=True, max_length=100, null=True)),
                ('so', models.CharField(blank=True, max_length=50, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ponto_de_rede', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('obs', models.CharField(max_length=400)),
                ('conjunto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conjunto', to='equipamento.Conjunto')),
            ],
        ),
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('obs', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=300)),
                ('tipo', models.CharField(blank=True, max_length=100)),
                ('descricao', models.CharField(max_length=400)),
                ('obs', models.CharField(max_length=400)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('marca', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marca', to='equipamento.Marca')),
            ],
        ),
        migrations.AddField(
            model_name='equipamento',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='modelo', to='equipamento.Modelo'),
        ),
    ]
